version: "3.9"

services:
  askmyreport:
    build: .
    ports:
      - "7860:7860"
    volumes:
      # mount local PDFs and vector DB so they survive container restarts
      - ./data:/app/data
      - ./db:/app/db
      - ./.env:/app/.env:ro
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    # optional GPU support (uncomment if host has nvidia-docker)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]